spring:
  mvc:
    servlet:
      path: /api
  jackson:
    mapper:
      accept-case-insensitive-properties: true
  datasource:
    url: ${db.url:jdbc:postgresql://localhost:5433/spring-angular-db}
    username: ${db.username:postgres}
    password: ${db.password:1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true
      connection-timeout: 60000
      maximum-pool-size: 50
logging:
  file:
    max-history: 20